engines:
  fixme:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - python
  git-legal:
    enabled: true
  gnu-complexity:
    enabled: true
  pep8:
    enabled: true
    checks:
      E111:
        enabled: false
      E114:
        enabled: false
      E266:
        enabled: false
      E701:
        enabled: false
      E402:
        enabled: false
  radon: 
    enabled: true
    config:
      threshold: "C"
      python_version: 2
  shellcheck:
    enabled: true

ratings:
   paths:
   - "*.sh"
   - "requirements.txt"
   - "protolint/**.py"

exclude_paths:
- "protolint_tests/**.py"
