language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y protobuf golang
install:
  - go get github.com/ckaznocha/protoc-gen-lint
  - make
script:
  - make test
