env:
  global:
    - CC_TEST_REPORTER_ID=d3deb90ab29eaa7d14ebb0d7934e43bbfbd742b9efb741f55f4331e324fde71a
    - CODECLIMATE_REPO_TOKEN=d3deb90ab29eaa7d14ebb0d7934e43bbfbd742b9efb741f55f4331e324fde71a
language: python
python:
  - "2.7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libprotobuf-dev golang
  - curl -OL https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip
  - unzip protoc-3.2.0-linux-x86_64.zip -d protoc3
  - sudo mv protoc3/bin/* /usr/local/bin/
  - sudo mv protoc3/include/* /usr/local/include/
  - go get github.com/ckaznocha/protoc-gen-lint
install:
  - make
script:
  - make test
after_script:
  - .env/bin/pip install codeclimate-test-reporter
  - .env/bin/codeclimate-test-reporter
