version: 2
jobs:
  build:
    docker:
      - image: sgammon/protoc-alpine:latest
    working_directory: ~/repo
    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: Install Dependencies
          command: |
            make environment dependencies 
            . .env/bin/activate

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: Build and Test
          command: |
            make

      - run:
          name: Upload Coverage
          command: |
            .env/bin/pip install --upgrade codeclimate-test-reporter
            CODECLIMATE_REPO_TOKEN=d3deb90ab29eaa7d14ebb0d7934e43bbfbd742b9efb741f55f4331e324fde71a .env/bin/codeclimate-test-reporter

      - store_artifacts:
          path: .env/tests
          destination: tests

      - store_artifacts:
          path: .env/coverage
          destination: coverage

